M48
; DRILL file {KiCad 7.0.7} date 2023 August 30, Wednesday 11:58:58
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-30T11:58:58-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X7.0026Y-6.3228
X7.0026Y-6.4212
X7.1995Y-6.1259
X7.3963Y-6.3228
X7.3963Y-6.4212
T2
X8.4543Y-4.8
T3
X2.0Y-1.6
X2.0Y-5.6
X7.5Y-1.6
X7.5Y-5.6
T0
M30
